#!/usr/bin/env node
// Generates everything derived from the app's content JSON:
//   backend/supabase/seed.sql                         objectives, spelling lists and questions
//   backend/supabase/functions/_shared/content.gen.ts avatar keys and content version for the API
//   web/lib/content.gen.json                          objectives, spelling lists and avatars for the website
//
// Run with `npm run seed` from backend/.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");
const contentDir = join(repo, "SPAG Buddy", "Resources", "Content");
const read = (name) => JSON.parse(readFileSync(join(contentDir, name), "utf8"));

/** Must match SpellingQuestionFactory.slug in the iOS app. */
export function slug(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function spellingQuestionId(listId, word) {
  return `spell-${listId}-${slug(word)}`;
}

function sql(value) {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

export function loadContent() {
  const manifest = read("manifest.json");
  const objectives = read(manifest.objectivesFile).objectives;
  const lists = read(manifest.spellingListsFile).lists;
  const avatars = read(manifest.avatarsFile).avatars;
  const questions = manifest.questionFiles.flatMap((file) => read(file).questions);

  const codes = new Set(objectives.map((o) => o.code));
  const ids = new Set();
  for (const q of questions) {
    if (!codes.has(q.objectiveCode)) throw new Error(`${q.id}: unknown objective ${q.objectiveCode}`);
    if (ids.has(q.id)) throw new Error(`Duplicate question id ${q.id}`);
    ids.add(q.id);
  }
  for (const list of lists) {
    if (!codes.has(list.objectiveCode)) throw new Error(`${list.id}: unknown objective ${list.objectiveCode}`);
  }
  return { manifest, objectives, lists, avatars, questions };
}

function buildSeed({ manifest, objectives, lists, questions }) {
  const version = manifest.contentVersion;
  const lines = [
    "-- Generated by backend/scripts/generate-seed.mjs. Do not edit by hand.",
    `-- Content version ${version}`,
    "begin;",
    "",
  ];

  for (const o of objectives) {
    lines.push(
      `insert into public.objectives (code, year_group, strand, title, child_title, rule) values (${[
        o.code, o.yearGroup, o.strand, o.title, o.childTitle, o.rule,
      ].map(sql).join(", ")}) on conflict (code) do update set year_group = excluded.year_group, strand = excluded.strand, title = excluded.title, child_title = excluded.child_title, rule = excluded.rule;`,
    );
  }
  lines.push("");

  for (const list of lists) {
    lines.push(
      `insert into public.spelling_lists (id, title, objective_code, year_groups, word_count) values (${[
        list.id, list.title, list.objectiveCode,
      ].map(sql).join(", ")}, '{${list.yearGroups.join(",")}}', ${list.words.length}) on conflict (id) do update set title = excluded.title, objective_code = excluded.objective_code, year_groups = excluded.year_groups, word_count = excluded.word_count;`,
    );
  }
  lines.push("");

  const upsertQuestion = (id, objectiveCode, listId, type, prompt, answers, sats) =>
    `insert into public.questions (id, objective_code, spelling_list_id, type, prompt, answers, sats_style, content_version) values (${[
      id, objectiveCode, listId, type, prompt,
    ].map(sql).join(", ")}, ${sql(JSON.stringify(answers))}::jsonb, ${sql(sats)}, ${sql(version)}) on conflict (id) do update set objective_code = excluded.objective_code, spelling_list_id = excluded.spelling_list_id, type = excluded.type, prompt = excluded.prompt, answers = excluded.answers, sats_style = excluded.sats_style, content_version = excluded.content_version;`;

  for (const q of questions) {
    lines.push(upsertQuestion(q.id, q.objectiveCode, null, q.type, q.prompt, q.answers, q.satsStyle ?? false));
  }
  for (const list of lists) {
    for (const { word } of list.words) {
      lines.push(upsertQuestion(spellingQuestionId(list.id, word), list.objectiveCode, list.id, "spelling", `Spell: ${word}`, [word], false));
    }
  }
  lines.push("", "commit;", "");
  return lines.join("\n");
}

function main() {
  const content = loadContent();
  const { manifest, objectives, lists, avatars } = content;

  writeFileSync(join(repo, "backend", "supabase", "seed.sql"), buildSeed(content));

  writeFileSync(
    join(repo, "backend", "supabase", "functions", "_shared", "content.gen.ts"),
    [
      "// Generated by backend/scripts/generate-seed.mjs. Do not edit by hand.",
      `export const CONTENT_VERSION = ${JSON.stringify(manifest.contentVersion)};`,
      `export const AVATAR_KEYS: readonly string[] = ${JSON.stringify(avatars.map((a) => a.key))};`,
      `export const SPELLING_LIST_IDS: readonly string[] = ${JSON.stringify(lists.map((l) => l.id))};`,
      `export const CONTENT_FILES: readonly string[] = ${JSON.stringify([
        "manifest.json", manifest.objectivesFile, manifest.spellingListsFile, manifest.avatarsFile, ...manifest.questionFiles,
      ])};`,
      "",
    ].join("\n"),
  );

  mkdirSync(join(repo, "web", "lib"), { recursive: true });
  writeFileSync(
    join(repo, "web", "lib", "content.gen.json"),
    JSON.stringify(
      {
        contentVersion: manifest.contentVersion,
        objectives,
        spellingLists: lists.map(({ words, ...rest }) => ({ ...rest, wordCount: words.length, words: words.map((w) => w.word) })),
        avatars,
        questions: content.questions.map((q) => ({
          id: q.id,
          objectiveCode: q.objectiveCode,
          type: q.type,
          prompt: q.prompt,
          choices: q.choices ?? [],
          answers: q.answers,
          satsStyle: q.satsStyle ?? false,
        })),
      },
      null,
      2,
    ) + "\n",
  );

  // The website's demo mode uses the same mastery, analytics, code and CSV rules as the API.
  for (const name of ["analytics", "codes", "csv"]) {
    const source = readFileSync(join(repo, "backend", "supabase", "functions", "_shared", `${name}.ts`), "utf8");
    writeFileSync(
      join(repo, "web", "lib", `${name}.gen.ts`),
      `// Copied from backend/supabase/functions/_shared/${name}.ts by backend/scripts/generate-seed.mjs. Do not edit.\n${source}`,
    );
  }

  const spellingCount = lists.reduce((n, l) => n + l.words.length, 0);
  console.log(
    `Content ${manifest.contentVersion}: ${objectives.length} objectives, ${content.questions.length} questions, ${spellingCount} spelling words, ${avatars.length} avatars`,
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
