// Generated by backend/scripts/generate-seed.mjs. Do not edit by hand.
export const CONTENT_VERSION = "2026.09.1";
export const AVATAR_KEYS: readonly string[] = ["fox","cat","dog","owl","frog","panda","lion","tiger","koala","rabbit","bear","penguin","unicorn","monkey","pig","cow","octopus","turtle","whale","bee","butterfly","hedgehog","chick","elephant","giraffe","zebra","dolphin","crab","snail","dragon","badger","squirrel"];
export const SPELLING_LIST_IDS: readonly string[] = ["y1-cew","y2-cew","y34-statutory","y56-statutory"];
export const CONTENT_FILES: readonly string[] = ["manifest.json","objectives.json","spelling-lists.json","avatars.json","year4.json"];
